//los types se usan para describir el estado de la apliación
export const AGREGAR_PRODUCTO="AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO="AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR";

export const COMENZAR_DESCARGA_PRODUCTO = "COMENZAR_DESCARGA_PRODUCTO";
export const DESCARGA_PRODUCTOS_EXITO = "DESCARGA_PRODUCTOS_EXISTO";
export const DESCARGA_PRODUCTOS_ERROR = "DESCARGA_PRODUCTOS_ERROR";

export const PRODUCTO_ELIMINAR = "OBTENER_PRODUCTO_ELIMINAR";
export const PRODUCTO_ELIMINADO_EXITO = "OBTENER_PRODUCTO_ELIMINADO_EXITO";
export const PRODUCTO_ELIMINADO_ERROR = "OBTENER_PRODUCTO_ELIMINADO_ERROR";

export const OBTENER_PRODUCTO_EDITAR = "OBTENER_PRODUCTO_EDITAR";
export const COMENZAR_EDICION_PRODUCTO = "COMENZAR_EDICION_PRODUCTO";
export const PRODUCTO_EDITADO_EXITO = "OBTENER_PRODUCTO_EDITADO_EXITO";
export const PRODUCTO_EDITADO_ERROR = "OBTENER_PRODUCTO_EDITADO_ERROR";

export const MOSTRAR_ALERTA ="MOSTRAR_ALERTA";
export const OCULAR_ALERTA ="OCULAR_ALERTA";